#=============================================================================#
#MIT License

#Copyright (c) 2023 沉默の金

#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:

#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.

#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
#=============================================================================#

name: Build OpenWrt-K
on:
  schedule:
    - cron: '0 4 * * *'
  push:
    paths:
      - 'config/**'
      - '.github/**'
      - 'files/**'
  pull_request:
            paths:
              - 'config/**'
              - '.github/**'
              - 'files/**'
  workflow_dispatch:
permissions:
  contents: write
  discussions: write
jobs:
  prepare:
    runs-on: ubuntu-22.04
    steps:
      - name: 准备环境
        run:  |
          sudo -E apt update
          sudo apt install -y curl git  rsync unzip wget sed
      
      - name: 将存储库签出到运行器
        uses: actions/checkout@v3
              
      - name: 建立工作文件夹
        run:  |
          cd $GITHUB_WORKSPACE
          mkdir -p download
          cd download
          export DOWNLOAD_ROOT_PATH="$(pwd)"
          echo "DOWNLOAD_ROOT_PATH=$DOWNLOAD_ROOT_PATH" >> $GITHUB_ENV
          mkdir -p lede
          mkdir -p Lienol
          mkdir -p immortalwrt
          mkdir -p wongsyrone
          mkdir -p passwall
          mkdir -p turboacc
          mkdir -p other
          cd $GITHUB_WORKSPACE
          mkdir -p cmzj_package
          cd cmzj_package
          export CMZJ_PACKAGE_ROOT_PATH="$(pwd)"
          echo "CMZJ_PACKAGE_ROOT_PATH=$CMZJ_PACKAGE_ROOT_PATH" >> $GITHUB_ENV
          mkdir -p turboacc
          cd $GITHUB_WORKSPACE
          mkdir -p cmzj_patch
          cd cmzj_patch
          export CMZJ_PATCH_ROOT_PATH="$(pwd)"
          echo "CMZJ_PATCH_ROOT_PATH=$CMZJ_PATCH_ROOT_PATH" >> $GITHUB_ENV
          mkdir -p $CMZJ_PATCH_ROOT_PATH/firewall4/patches/
          mkdir -p $CMZJ_PATCH_ROOT_PATH/libnftnl/patches/
          mkdir -p $CMZJ_PATCH_ROOT_PATH/nftables/patches/          

      - name: 克隆源代码
        working-directory:  ${{ env.DOWNLOAD_ROOT_PATH }}
        run:  |
          cd lede
          git clone https://github.com/coolsnowwolf/lede
          git clone https://github.com/coolsnowwolf/luci
          git clone https://github.com/coolsnowwolf/packages 
          cd $DOWNLOAD_ROOT_PATH        
          cd Lienol
          git clone https://github.com/Lienol/openwrt-package
          cd $DOWNLOAD_ROOT_PATH
          cd immortalwrt
          git clone https://github.com/immortalwrt/luci
          cd $DOWNLOAD_ROOT_PATH
          cd wongsyrone
          git clone https://github.com/wongsyrone/lede-1
          cd $DOWNLOAD_ROOT_PATH
          cd passwall
          git clone https://github.com/xiaorouji/openwrt-passwall -b luci
          mv ./openwrt-passwall/luci-app-passwall ./luci-app-passwall
          rm -rf openwrt-passwall
          git clone https://github.com/xiaorouji/openwrt-passwall
          git clone https://github.com/xiaorouji/openwrt-passwall2
          cd $DOWNLOAD_ROOT_PATH
          cd turboacc
          git clone https://github.com/chenmozhijin/turboacc
          mv ./turboacc/luci-app-turboacc ./luci-app-turboacc
          rm -rf ./turboacc
          git clone https://github.com/chenmozhijin/turboacc -b package
          git clone https://github.com/fullcone-nat-nftables/nft-fullcone
          cd $DOWNLOAD_ROOT_PATH
          cd other
          git clone https://github.com/rufengsuixing/luci-app-adguardhome
          git clone https://github.com/jerrykuku/luci-app-argon-config
          git clone https://github.com/csrutil/OpenWrt-NIC-Drivers
          git clone https://github.com/lisaac/luci-app-diskman
          git clone https://github.com/sirpdboy/luci-app-netdata
          git clone https://github.com/sirpdboy/NetSpeedTest
          git clone https://github.com/tty228/luci-app-serverchan
          git clone https://github.com/jerrykuku/luci-theme-argon

      - name: 复制到cmzj_package
        run: |
          cp -r $DOWNLOAD_ROOT_PATH/lede/luci/applications/luci-app-baidupcs-web $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/luci/applications/luci-app-rclone $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/luci/applications/luci-app-syncdial $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/luci/applications/luci-app-usb-printer $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/luci/applications/luci-app-qbittorrent $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/luci/applications/luci-app-vlmcsd $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/luci/applications/luci-app-zerotier $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/luci/applications/luci-app-webadmin $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/luci/applications/luci-app-cifs-mount $CMZJ_PACKAGE_ROOT_PATH/         
          cp -r $DOWNLOAD_ROOT_PATH/lede/packages/net/vlmcsd $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/packages/net/baidupcs-web $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/packages/net/qBittorrent $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/packages/net/qBittorrent-static $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/packages/libs/rblibtorrent $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/packages/libs/qtbase $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/packages/libs/qttools $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/lede/package/lean/ipv6-helper $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/lede/package/lean/ddns-scripts_aliyun $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/lede/package/lean/ddns-scripts_dnspod $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/lede/package/lean/r8168 $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/lede/lede/package/lean/shortcut-fe $CMZJ_PACKAGE_ROOT_PATH/turboacc/
          cp -r $DOWNLOAD_ROOT_PATH/immortalwrt/luci/applications/luci-app-transmission $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/Lienol/openwrt-package/luci-app-fileassistant $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/Lienol/openwrt-package/luci-app-socat $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/passwall/luci-app-passwall $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/passwall/openwrt-passwall $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/passwall/openwrt-passwall2 $CMZJ_PACKAGE_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/turboacc/turboacc $CMZJ_PACKAGE_ROOT_PATH/turboacc/
          cp -r $DOWNLOAD_ROOT_PATH/turboacc/nft-fullcone $CMZJ_PACKAGE_ROOT_PATH/turboacc/
          cp -r $DOWNLOAD_ROOT_PATH/other/* $CMZJ_PACKAGE_ROOT_PATH/
          cd $CMZJ_PACKAGE_ROOT_PATH && ls

      - name: 修改Makefile文件
        working-directory:  ${{ env.CMZJ_PACKAGE_ROOT_PATH }}
        run: |
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./luci-app-vlmcsd/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./luci-app-webadmin/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./luci-app-zerotier/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./luci-app-cifs-mount/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./luci-app-baidupcs-web/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./luci-app-rclone/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./luci-app-syncdial/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./luci-app-usb-printer/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./luci-app-transmission/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./luci-app-qbittorrent/Makefile         

      - name: 创建软连接以修复中文支持
        working-directory:  ${{ env.CMZJ_PACKAGE_ROOT_PATH }}
        run: |
          ln -s zh-cn ./luci-app-webadmin/po/zh_Hans
          ln -s zh-cn ./luci-app-netdata/po/zh_Hans
          ln -s zh-cn ./luci-app-vlmcsd/po/zh_Hans
          ln -s zh-cn ./luci-app-zerotier/po/zh_Hans
          ln -s zh-cn ./luci-app-usb-printer/po/zh_Hans
          ln -s zh-cn ./luci-app-qbittorrent/po/zh_Hans

      - name: 修改luci-app-netdata
        working-directory:  ${{ env.CMZJ_PACKAGE_ROOT_PATH }}
        run: |
          sed -i 's/setting")/netdata")/' ./luci-app-netdata/luasrc/controller/netdata.lua
          sed -i 's/("Base Setting"), 20/("Base Setting"), 30/' ./luci-app-netdata/luasrc/controller/netdata.lua
          sed -i 's/("NetData"), 30/("NetData"), 20/' ./luci-app-netdata/luasrc/controller/netdata.lua

      - name: 复制到cmzj_patch
        run: |
          cp $DOWNLOAD_ROOT_PATH/lede/lede/target/linux/generic/hack-5.10/952-net-conntrack-events-support-multiple-registrant.patch $CMZJ_PATCH_ROOT_PATH/
          cp $DOWNLOAD_ROOT_PATH/lede/lede/target/linux/generic/hack-5.10/953-net-patch-linux-kernel-to-support-shortcut-fe.patch $CMZJ_PATCH_ROOT_PATH/
          cp $DOWNLOAD_ROOT_PATH/lede/lede/target/linux/generic/hack-5.10/982-add-bcm-fullconenat-support.patch $CMZJ_PATCH_ROOT_PATH/
          cp -r $DOWNLOAD_ROOT_PATH/turboacc/turboacc/firewall4-7ae5e14bbd7265cc67ec870c3bb0c8e197bb7ca9/firewall4/patches/* $CMZJ_PATCH_ROOT_PATH/firewall4/patches
          cp -r $DOWNLOAD_ROOT_PATH/turboacc/turboacc/libnftnl-1.2.1/libnftnl/patches/* $CMZJ_PATCH_ROOT_PATH/libnftnl/patches
          cp -r $DOWNLOAD_ROOT_PATH/turboacc/turboacc/nftables-1.0.2/nftables/patches/* $CMZJ_PATCH_ROOT_PATH/nftables/patches         
          
      - name: 上传 cmzj_package
        uses: actions/upload-artifact@v3
        with:
          name: cmzj_package
          path: cmzj_package

      - name: 上传 cmzj_patch
        uses: actions/upload-artifact@v3
        with:
          name: cmzj_patch
          path: cmzj_patch
