#MIT License

#Copyright (c) 2023 沉默の金

#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:

#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.

#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

name: Build OpenWrt-K


on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-22.04


    steps:

      - uses: actions/checkout@v3

      - name: 清理空间
        run:  |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql /etc/php
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo -E apt update
          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* moby* snap*
      
      
      - name: 安装编译依赖并建立工作文件夹
        run: |
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo -E apt update
          sudo -E apt -y full-upgrade
          sudo -E apt update -y && sudo apt full-upgrade -y && sudo apt install -y ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils clang g++ python3-distutils rsync unzip zlib1g-dev wget
          sudo -E systemctl daemon-reload 
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo timedatectl set-timezone "Asia/Shanghai"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
      - name: 下载源代码
        working-directory: /workdir
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git
          mkdir -p package
          cd package
          mkdir -p chen
          mkdir -p cmzj_package
          cd chen
          git clone https://github.com/Lienol/openwrt-package
          git clone https://github.com/immortalwrt/luci
          git clone https://github.com/xiaorouji/openwrt-passwall -b luci
          git clone https://github.com/wongsyrone/lede-1
          git clone https://github.com/coolsnowwolf/lede
          git clone https://github.com/chenmozhijin/turboacc -b package
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cd ..
          cd ..
          cd cmzj_package
          mkdir -p turboacc
          git clone https://github.com/rufengsuixing/luci-app-adguardhome
          git clone https://github.com/jerrykuku/luci-app-argon-config
          git clone https://github.com/csrutil/OpenWrt-NIC-Drivers
          git clone https://github.com/lisaac/luci-app-diskman
          git clone https://github.com/sirpdboy/luci-app-netdata
          git clone https://github.com/sirpdboy/NetSpeedTest
          git clone https://github.com/xiaorouji/openwrt-passwall
          #git clone https://github.com/xiaorouji/openwrt-passwall2
          git clone https://github.com/davidtall/openwrt-passwall2
          git clone https://github.com/tty228/luci-app-serverchan
          git clone https://github.com/jerrykuku/luci-theme-argon
          cd turboacc
          git clone https://github.com/fullcone-nat-nftables/nft-fullcone
          git clone https://github.com/chenmozhijin/turboacc
          mv ./turboacc/luci-app-turboacc ./
          rm -rf ./turboacc
      - name: 复制源代码修复中文支持与Makefile文件
        working-directory: /workdir/package
        run: |
          cp -r ./chen/luci/applications/luci-app-transmission ./cmzj_package/
          cp -r ./chen/openwrt-package/luci-app-fileassistant ./cmzj_package/
          cp -r ./chen/openwrt-package/luci-app-socat ./cmzj_package/
          cp -r ./chen/lede/feeds/luci/applications/luci-app-baidupcs-web ./cmzj_package/
          cp -r ./chen/lede/feeds/luci/applications/luci-app-rclone ./cmzj_package/
          cp -r ./chen/lede/feeds/luci/applications/luci-app-syncdial ./cmzj_package/
          cp -r ./chen/lede/feeds/luci/applications/luci-app-usb-printer ./cmzj_package/
          cp -r ./chen/lede/feeds/luci/applications/luci-app-qbittorrent ./cmzj_package/
          cp -r ./chen/lede/feeds/luci/applications/luci-app-vlmcsd ./cmzj_package/
          cp -r ./chen/lede/feeds/packages/net/vlmcsd ./cmzj_package/
          cp -r ./chen/lede/feeds/packages/net/baidupcs-web ./cmzj_package/
          cp -r ./chen/lede/feeds/packages/net/qBittorrent ./cmzj_package/
          cp -r ./chen/lede/feeds/packages/net/qBittorrent-static ./cmzj_package/
          cp -r ./chen/lede/feeds/packages/libs/rblibtorrent ./cmzj_package/
          cp -r ./chen/lede/feeds/packages/libs/qtbase ./cmzj_package/
          cp -r ./chen/lede/feeds/packages/libs/qttools ./cmzj_package/
          cp -r ./chen/lede/feeds/luci/applications/luci-app-zerotier ./cmzj_package/
          cp -r ./chen/lede/feeds/luci/applications/luci-app-webadmin ./cmzj_package/
          cp -r ./chen/lede/feeds/luci/applications/luci-app-cifs-mount ./cmzj_package/
          cp -r ./chen/lede/package/lean/ipv6-helper ./cmzj_package/
          cp -r ./chen/lede/package/lean/ddns-scripts_aliyun ./cmzj_package/
          cp -r ./chen/lede/package/lean/ddns-scripts_dnspod ./cmzj_package/
          cp -r ./chen/lede/package/lean/r8168 ./cmzj_package/
          cp -r ./chen/lede/package/lean/shortcut-fe ./cmzj_package/turboacc/
          cp -r ./chen/openwrt-passwall/luci-app-passwall  ./cmzj_package/
          cp -r ./cmzj_package/luci-app-argon-config/po/zh_Hans ./cmzj_package/luci-app-webadmin/po/
          cp -r ./cmzj_package/luci-app-argon-config/po/zh_Hans ./cmzj_package/luci-app-netdata/po/
          cp -r ./cmzj_package/luci-app-argon-config/po/zh_Hans ./cmzj_package/luci-app-vlmcsd/po/
          cp -r ./cmzj_package/luci-app-argon-config/po/zh_Hans ./cmzj_package/NetSpeedTest/luci-app-netspeedtest/po/
          cp -r ./cmzj_package/luci-app-argon-config/po/zh_Hans ./cmzj_package/luci-app-zerotier/po/
          cp -r ./cmzj_package/luci-app-argon-config/po/zh_Hans ./cmzj_package/luci-app-usb-printer/po/
          cp -r ./cmzj_package/luci-app-argon-config/po/zh_Hans ./cmzj_package/luci-app-qbittorrent/po/
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./cmzj_package/turboacc/luci-app-turboacc/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./cmzj_package/luci-app-vlmcsd/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./cmzj_package/luci-app-webadmin/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./cmzj_package/luci-app-zerotier/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./cmzj_package/luci-app-cifs-mount/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./cmzj_package/luci-app-baidupcs-web/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./cmzj_package/luci-app-rclone/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./cmzj_package/luci-app-syncdial/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./cmzj_package/luci-app-usb-printer/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./cmzj_package/luci-app-transmission/Makefile
          sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./cmzj_package/luci-app-qbittorrent/Makefile
          sed -i 's/setting")/netdata")/' ./cmzj_package/luci-app-netdata/luasrc/controller/netdata.lua
          sed -i 's/("Base Setting"), 20/("Base Setting"), 30/' ./cmzj_package/luci-app-netdata/luasrc/controller/netdata.lua
          sed -i 's/("NetData"), 30/("NetData"), 20/' ./cmzj_package/luci-app-netdata/luasrc/controller/netdata.lua
      - name: 切换到新的稳定版分支
        working-directory: /workdir/openwrt
        run: git checkout v22.03.3

      - name: 复制cmzj_package 打补丁
        working-directory: /workdir
        run: |
          cp -r ./package/cmzj_package ./openwrt/package/cmzj_package
          mkdir -p ./openwrt/package/network/config/firewall4/patches/
          mkdir -p ./openwrt/package/libs/libnftnl/patches/
          mkdir -p ./openwrt/package/network/utils/nftables/patches/
          cp -r ./package/chen/turboacc/firewall4-7ae5e14bbd7265cc67ec870c3bb0c8e197bb7ca9/firewall4/patches/* ./openwrt/package/network/config/firewall4/patches
          cp -r ./package/chen/turboacc/libs-1.2.1/libnftnl/patches/* ./openwrt/package/libs/libnftnl/patches
          cp -r ./package/chen/turboacc/nftables-1.0.2/nftables/patches/* ./openwrt/package/network/utils/nftables/patches
          rm -rf ./package
      - name: 修复问题
        working-directory: /workdir/openwrt
        run: |
          sed -i 's/-full//' ./include/target.mk 
          sed -i 's/dnsmasq/dnsmasq-full/g' ./include/target.mk 
          sed -i 's/256/1024/' ./target/linux/x86/image/Makefile
      
      - name: 更新 feeds 
        working-directory: /workdir/openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 更新smartdns
        working-directory: /workdir/openwrt
        run: |
          WORKINGDIR="`pwd`/feeds/packages/net/smartdns"
          mkdir $WORKINGDIR -p
          rm $WORKINGDIR/* -fr
          wget https://github.com/pymumu/openwrt-smartdns/archive/master.zip -O $WORKINGDIR/master.zip
          unzip $WORKINGDIR/master.zip -d $WORKINGDIR
          mv $WORKINGDIR/openwrt-smartdns-master/* $WORKINGDIR/
          rmdir $WORKINGDIR/openwrt-smartdns-master
          rm $WORKINGDIR/master.zip
          LUCIBRANCH="master" #更换此变量
          WORKINGDIR="`pwd`/feeds/luci/applications/luci-app-smartdns"
          mkdir $WORKINGDIR -p
          rm $WORKINGDIR/* -fr
          wget https://github.com/pymumu/luci-app-smartdns/archive/${LUCIBRANCH}.zip -O $WORKINGDIR/${LUCIBRANCH}.zip
          unzip $WORKINGDIR/${LUCIBRANCH}.zip -d $WORKINGDIR
          mv $WORKINGDIR/luci-app-smartdns-${LUCIBRANCH}/* $WORKINGDIR/
          rmdir $WORKINGDIR/luci-app-smartdns-${LUCIBRANCH}
          rm $WORKINGDIR/${LUCIBRANCH}.zip
      
      - name: 安装 feeds 
        working-directory: /workdir/openwrt
        run: ./scripts/feeds install -a

      - name: 复制自定义文件并加载自定义配置
        run: |
          cp -r files /workdir/openwrt/files
          chmod 755 ./files/usr/bin/AdGuardHome/AdGuardHome
          chmod 755 ./files/etc/uci-defaults/99_chenmozhijin
          cat ./config/target.config >> /workdir/openwrt/.config
          cat ./config/luci.config >> /workdir/openwrt/.config
          cat ./config/utilities.config >> /workdir/openwrt/.config
          cat ./config/network.config >> /workdir/openwrt/.config
          cat ./config/other.config >> /workdir/openwrt/.config
          cat ./config/kmod.config >> /workdir/openwrt/.config
          cat ./config/image.config >> /workdir/openwrt/.config
      
      - name: 更新AdGuardHome核心
        working-directory: /workdir/openwrt  
        run: |
          mkdir -p ./files/usr/bin/AdGuardHome/tmp
          rm ./files/usr/bin/AdGuardHome/tmp/* -fr        
          latest_ver="$(curl https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest 2>/dev/null|grep -E 'tag_name' |grep -E 'v[0-9.]+' -o 2>/dev/null)"
          Archt="$(rm Archt && sed -n '/^CONFIG_TARGET_.*=y/p' .config > Archt0 && sed -n '/^CONFIG_TARGET_.*_.*=y/!p' Archt0 > Archt && rm Archt0 && sed -i 's/CONFIG_TARGET_//' Archt && sed -i 's/=y//' Archt && cat Archt)"
          case $Archt in
          "i386")
          Arch="386"
          ;;
          "i686")
          Arch="386"
          ;;
          "x86")
          Arch="amd64"
          ;;
          "mipsel")
          Arch="mipsle"
          ;;
          "mips64el")
          Arch="mips64le"
          Arch="mipsle"
          echo -e "mips64el use $Arch may have bug" 
          ;;
          "mips")
          Arch="mips"
          ;;
          "mips64")
          Arch="mips64"
          Arch="mips"
          echo -e "mips64 use $Arch may have bug" 
          ;;
          "arm")
          Arch="arm"
          ;;
	  "aarch64")
          Arch="arm64"
          ;;
          "powerpc")
          Arch="ppc"
          echo -e "error not support $Archt" 
          EXIT 1
          ;;
          "powerpc64")
          Arch="ppc64"
          echo -e "error not support $Archt" 
          EXIT 1
          ;;
          *)
          echo -e "error not support $Archt if you can use offical release please issue a bug" 
          EXIT 1
          ;;
          esac
          wget https://github.com/AdguardTeam/AdGuardHome/releases/download/${latest_ver}/AdGuardHome_linux_${Arch}.tar.gz -O ./files/usr/bin/AdGuardHome/tmp/AdGuardHome.tar.gz
          tar -zxf "./files/usr/bin/AdGuardHome/tmp/AdGuardHome.tar.gz" -C "./files/usr/bin/AdGuardHome/tmp/"
          mv -f ./files/usr/bin/AdGuardHome/tmp/AdGuardHome/AdGuardHome ./files/usr/bin/AdGuardHome
          rm -rf ./files/usr/bin/AdGuardHome/tmp

      - name: 生成配置文件
        working-directory: /workdir/openwrt
        run: |
          make defconfig
          ./scripts/diffconfig.sh

      - name: 下载 dl 库
        working-directory: /workdir/openwrt
        run: |
          make download -j16
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
          make download -j16 || make download -j1 V=s


      - name: 编译固件 
        working-directory: /workdir/openwrt
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
      
      - name: Prepare artifact
        working-directory: /workdir/openwrt      
        run: |
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/
          export BUILD_DATE=$(date +"%Y-%m-%d")
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
      - name: 上传 buildinfo
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_buildinfo
          path: /workdir/openwrt/artifact/buildinfo/

      - name: 上传 package
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_package
          path: /workdir/openwrt/artifact/package/

      - name: 上传 firmware
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_firmware
          path: /workdir/openwrt/bin/targets/
      
      - name: 上传到 Release
        uses: ncipollo/release-action@v1.8.0
        with:
          name: OpenWrt-K
          allowUpdates: true
          replacesArtifacts: true
          body: 编译于${{ env.BUILD_DATE }}
          artifacts: /workdir/openwrt/bin/targets/x86/64/*
