# This is a basic workflow to help you get started with Actions

name: Build OpenWrt-K

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Generate configuration file
        working-directory: /
        run: |
          mkdir -p ./workdir/openwrt/
          cp -r files /workdir/openwrt/files
          cat /config/target.config >> /workdir/openwrt/.config
          cat config/luci.config >> /workdir/openwrt/.config
          cat config/utilities.config >> /workdir/openwrt/.config
          cat config/network.config >> /workdir/openwrt/.config
          cat config/other.config >> /workdir/openwrt/.config
          cat config/kmod.config >> /workdir/openwrt/.config
          cat config/image.config >> /workdir/openwrt/.config
          cd /workdir/openwrt
          ls
          cd files
          ls

    
